### ISSUE TITLE
How to clone a new game like this？

### ISSUE THREAD

**Issue by ArtinHuang** [feisuzhu/thbattle#128]
About all，from my perspective，**thbattle is an interesting game.**

But as a python beginner,if I want to clone a new game like this.How do I start the first step——how to read the source code and where is the main program extrance？

**Comment by feisuzhu** [comment]
Arghh……
Documents are actually non-existent... Sorry about that...

Client entrance: https://github.com/feisuzhu/thbattle/blob/master/src/start_client.py
Server entrance: https://github.com/feisuzhu/thbattle/blob/master/src/start_server.py

Game Mode Entrance:
https://github.com/feisuzhu/thbattle/blob/master/src/gamepack/thb/thbidentity.py#L142

Typical character: Koakuma
https://github.com/feisuzhu/thbattle/blob/master/src/gamepack/thb/characters/koakuma.py

**Comment by feisuzhu** [comment]
IMPORTANT:

Game logics are kept synchronized between server and clients, they are running exact same code path except low level communication code and few places with explicit `if Game.CLIENT_SIDE` like statements.

**Comment by ArtinHuang** [comment]
thanks for your reply
