### ISSUE TITLE
(off topic)

### ISSUE THREAD

**Issue by ThinkLoudly** [feisuzhu/thbattle#134]
不好意思歪个楼。

喜欢作者头像，Google搜不到，请问下出自哪里，画师是谁？谢谢

**Comment by feisuzhu** [comment]
抱歉刚看到…………………………………………

画师是 和茶，搜不到是应该的…… 这是请她画的

**Comment by ThinkLoudly** [comment]
@feisuzhu 谢谢谢谢，知道画师是谁就很满足了
