### ISSUE TITLE
风酱的新系统设计

### ISSUE THREAD

**Issue by feisuzhu** [feisuzhu/thbattle#149]
https://www.kdocs.cn/l/sEVsJcVKj

**Comment by yicong1406410220** [comment]
要留住玩家让玩家有目标可刷，需要建立经验值或金币系统让玩家可以赚取，并解锁相应的游戏内容供玩家获得成就感。是正确的，但是我不同意+1UP，这样会破坏游戏的平衡性，签到系统会使玩家过劳。应该使用任务系统来代替，类似于炉石传说的任务系统。对于没时间玩家可以攒3天任务再一起完成。也能提高玩家的游戏次数。
核心付费内容应该以角色皮肤，音乐，卡牌皮肤，卡背皮肤来建立。而角色都能以p金币解锁，并且对于没有时间的玩家可以使用等量的F砖石来提前解锁。作为高级货币f砖石在任何p金币能使用的地方使用。
增加周免角色，每个玩家应该有一定数量的周免角色，每周刷新，以防新入坑的玩家进入坑无角色可用的状态。
可用通过售卖角色捆绑包，只能用F砖石购买，来让工作比较忙的玩家用金钱换取时间。

**Comment by yicong1406410220** [comment]
为了提高老玩家收集的生命周期，减少新手入坑的难度，可以主推抽奖系统，把金币角色的价格都设置的比较高。玩家能通过价格比较低的抽奖抽取角色。每次必中1名角色单角色可能重复，重复的角色会转化为碎片，6个碎片可以直接兑换1个角色。因为卡池原因你拥有的角色越多，抽取到新角色的难度越大。角色可以按技能难易度分为普通，稀有，传说。相似的类型。

**Comment by feisuzhu** [comment]
@yicong1406410220 thx~
看起来都很合理，会考虑进去的

**Comment by Aated** [comment]
不要刷新卡，不要碎片机制，不要抽卡机制

**Comment by Aated** [comment]
第一，房间列表与匹配机制要同时存在，本游首先是人口基数基数问题，其次是游戏玩家问题。
跟朋友一起玩的感觉，就必须要加入队伍与好友系统，单单的匹配系统实在是太煞风景，社交的元素会被磨灭殆尽。所以在队伍与好友功能未完善之前，保留房间列表功能。

第二，我个人不推荐每日任务与每日签到
这个游戏本身我就很希望是偶尔闲暇的时候去玩玩，无论是市场竞争力还是游戏时间分配，我都很难花时间去一点点做这个每日任务，更不要说上班打卡一样的每日签到。
而且一旦每日任务与签到存在，必然会出现对资源的攀比与挂念，这符合一个休闲游戏的定义吗？

第三，反对碎片化角色抽奖与角色稀有度分级与角色购买
碎片化角色：恶心至极的王者套路，通过廉价的套路不断压榨玩家的耐心。有这个时间我为什么不去直接兑换角色而是选择不稳定的抽卡。既然有直接购买角色的渠道，抽奖是否会显得鸡肋。而且碎片化角色的套路令人感到反感，我不会将自己的资源，浪费在无聊的抽卡上面，选择稳妥的直接购买会更深入人心。

碎片化皮肤：我觉得这个是可行的，通过积攒资源对皮肤进行一个长期的获取。与直接免费购买角色的渠道来说，这是两个完全不同的性质

角色稀有度分级：这个我就更搞不懂了，一个角色的稀有度你要用什么标准去评判？操作强度？所以越来越紧跟三国杀的老路了是吗？我们希望的是有一个公平公正的环境，而不是有钱的人砸钱拿强将，欧皇拿强将进行炫耀。这对正常玩家的获取造成了极大的不公平性，你们也不缺钱，自然不要忘记休闲游戏的定义。

反对角色购买：老玩家不接受，没有太多精力去玩这个游戏，对于资源获取力较弱，从公平游戏而言，对角色的获取力度已经开始对新老玩家不公平了。

**Comment by iRinwind** [comment]
半年来我思考了很久。之后开个新issue阐述一下我的想法。
你所担忧的大部分问题不会存在。
