### ISSUE TITLE
希望能有配套的客户端代码进行学习。

### ISSUE THREAD

**Issue by yicong1406410220** [feisuzhu/thbattle#219]
我在项目中没有找到python游戏客户端，或者unity客户端的位置，能告诉我他们的位置吗？

**Comment by a395338563** [comment]
> 我在项目中没有找到python游戏客户端，或者unity客户端的位置，能告诉我他们的位置吗？

python客户端ui在\src\thb\ui，逻辑是双端共享的，至于unity客户端，虽然没上传，我没猜错的话也只是写了一套ui，逻辑是调用python层的。

**Comment by baisebaoma** [comment]
好像整个都是客户端呀（其实我想要服务端但是找不到）

**Comment by feisuzhu** [comment]
> > 我在项目中没有找到python游戏客户端，或者unity客户端的位置，能告诉我他们的位置吗？
> 
> python客户端ui在\src\thb\ui，逻辑是双端共享的，至于unity客户端，虽然没上传，我没猜错的话也只是写了一套ui，逻辑是调用python层的。

unity 客户端没有放出来，里面很烂遭，放出来你也跑不起来……
以及是的，unity 那边就是一套 ui

**Comment by feisuzhu** [comment]
> 我在项目中没有找到python游戏客户端，或者unity客户端的位置，能告诉我他们的位置吗？

python 客户端 master 分支就有

**Comment by feisuzhu** [comment]
> 好像整个都是客户端呀（其实我想要服务端但是找不到）

服务端入口是 `start_server.py`
