### ISSUE TITLE
UI 元素制作

### ISSUE THREAD

**Issue by feisuzhu** [feisuzhu/thbattle#233]
- [x] 身份的图标还需要 守矢、博丽
- [x] 身份的图标还需要 「？」
- [x] 卡牌还需要一个「这是装备牌」的标记（在明牌标记旁边）
- [x] 提示的地方确定和取消两个按钮是不够用的，大多数技能发动时的提示按钮都是跟技能相关的，比如小伞的惊吓的按钮是4个花色。需要给出文字的样式说明（参考第一条）以及不带文字的底图。

**Comment by feisuzhu** [comment]
@iRinwind

**Comment by feisuzhu** [comment]
角色卡片上还缺失的元素：

- [ ] 逃跑和掉线的指示
- [ ] miss后的设计
- [ ]「正在输入」和「当前回合」的指示
- [ ] 还没有选人空白时候的样式
- [ ]「选中」的效果
- [ ]  容纳「标记」的地方

**Comment by feisuzhu** [comment]
游戏中出现的 UI 面板：
- [ ] 城管执法的选牌界面（一般的「选择其他角色一张牌」界面）
- [ ] 河童的「匠心」选牌界面
- [ ] 秦心的「希望之面」选牌界面
- [ ] 蓝的「神算」选牌界面

**Comment by iRinwind** [comment]
> * [x]  身份的图标还需要 守矢、博丽
> * [x]  身份的图标还需要 「？」
> * [x]  卡牌还需要一个「这是装备牌」的标记（在明牌标记旁边）
> * [x]  提示的地方确定和取消两个按钮是不够用的，大多数技能发动时的提示按钮都是跟技能相关的，比如小伞的惊吓的按钮是4个花色。需要给出文字的样式说明（参考第一条）以及不带文字的底图。

此issue已解决，上传至 UI_images 文件夹

**Comment by iRinwind** [comment]
该 issue 提及的界面已设计完毕
