### ISSUE TITLE
大狸子的选牌需要同时能选择手牌和期望变成的牌，现在的设计「期望变成的牌」直接覆盖掉手牌的位置了

### ISSUE THREAD

**Issue by iRinwind** [feisuzhu/thbattle#241]

**Comment by iRinwind** [comment]
点击变化按钮后，先是这样一个界面选要变成的牌；这过程里，如果手牌中一张非延时符卡都没有，非延时符卡部分的选项全部变灰；如果一张基本牌都没有，基本牌的选项也全部变灰。
![A541FD7B4C0B3A694AC1EE6FFF95D0BA](https://user-images.githubusercontent.com/25262465/126025846-332a149f-8f5e-435f-a1c6-21d9d6d3c446.jpg)

然后再回到手牌界面选择两张牌。
选两张牌的时候，第一张牌必须选择一张符合要求的（其他变灰）；第二张牌则可以任选。

**Comment by iRinwind** [comment]
![ADDBA5B13F19B77A0078DB379A02900C](https://user-images.githubusercontent.com/25262465/126029550-84f273c0-ca40-4d8e-b29b-025e3cb597fa.jpg)
优化方案：用选牌窗口选择想要使用的牌，下面保留手牌区选择想要变化的牌

**Comment by Aated** [comment]
还有一点：栗子可变化的牌太多，需在选牌界面进行多行排序
第一行：三张基本
第二行：单目标符卡
第三行：多目标符卡

**Comment by baisebaoma** [comment]
尊敬的女士/先生 您好，
感谢您的来信。这是一封自动回复邮件，代表您的邮件已送达至我的邮箱。在我检查邮箱时，我会立即回复您。感谢您的等待。Baisebaoma
