### ISSUE TITLE
少女选择在身份发表之前

### ISSUE THREAD

**Issue by lolisa** [feisuzhu/thbattle#91]
Is this intended or a misimplementation? Really stressful because different character work for different identity...

**Comment by feisuzhu** [comment]
Which mode?

I just checked all game modes, didn't find the issue you described.

**Comment by lolisa** [comment]
Identity mode.
Can you present me a pic showing where I can see my identity before I choose my girl?

**Comment by lolisa** [comment]
OK I found it.
