### ISSUE TITLE
Warning and Segfault (does not effect gameplay)

### ISSUE THREAD

**Issue by MarisaKirisame** [feisuzhu/thbattle#98]
On enter:
/home/marisa/Work/thbattle/src/pyglet/gl/gl_info.py:166: UserWarning: No GL context created yet.
  warnings.warn('No GL context created yet.')

On exit:
AL lib: (EE) alc_cleanup: 1 device not closed
Segmentation fault

**Comment by feisuzhu** [comment]
Python client abandoned.
